### PR TITLE
Enable black github actions workflow

### PR DESCRIPTION
**Pull request by soxofaan**
Issue #16

### CODE REVIEW

**Comment by soxofaan** [comment]
@GriffinBabe   under #16 I already merged #21  to have a minimal lint action active in github actions

But this PR#22 is quite a large code style fixup, which could easily conflict with ongoing work by you, so I'm not going to merge this blindly

**Comment by soxofaan** [comment]
changed this PR to a draft PR, because it is probably too conflict-risky

alternative:
- first introduce "darker" as github action linter, to enforce that at least edited/new code is black compatible, this approach should not cause sudden conflicts on open branhces

**Comment by soxofaan** [comment]
started with PR #39 to first start with "darker" instead of "black"

**Comment by soxofaan** [comment]
as discussed: we first want to get #38 merged before continuing working on this #22 or #39

**Review by GriffinBabe — APPROVED** [review]

**Comment by soxofaan** [comment]
as discussed, merged this now

**Pull request merged**
