### PR TITLE
split up unit and integration tests

### PR DESCRIPTION
**Pull request by HansVRP**

### CODE REVIEW

**Comment by HansVRP** [comment]
(still waiting for the integration tests to come through)

**Review by VincentVerelst — COMMENTED** [review]
- What is the purpose of the `test_openeo_gfmap` folder? 
- For the unit tests: can we maybe use the same folder structure as in `src`?

**Comment by HansVRP** [comment]
https://jenkins.vgt.vito.be/job/openEO/job/openeo-gfmap/view/change-requests/job/PR-163/

integration tests are passing

**Comment by HansVRP** [comment]
@VincentVerelst ready for re-review

**Review by VincentVerelst — APPROVED** [review]
Looks good to me!

**Comment by HansVRP** [comment]
integration tests are failing, will look into it

**Pull request merged**
